name: Build BIBI OS ISO

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build equivs

      - name: Fake missing packages
        run: |
          for pkg in syslinux-themes-ubuntu-oneiric gfxboot-theme-ubuntu; do
            equivs-control $pkg
            sed -i "s/Package:.*/Package: $pkg/" $pkg
            equivs-build $pkg
            sudo dpkg -i ${pkg}_*.deb
          done

      - name: Build ISO
        run: sudo lb build

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: BIBI-OS
          path: "*.iso"
